config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  
  devise_for :users, controllers: {
          sessions: 'users/sessions',
          registrations: 'users/registrations'
        }
  
  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        sessions: 'api/v1/users/sessions',
        registrations: 'api/v1/users/registrations'

      }
      resources :articles
    end
  end

  resources :articles do
    resources :comments
  end
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :body, presence: true, length: { minimum: 10 }
  
  def comment_count
    comments.count
  end
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < ApplicationController
  before_action :authenticate_user!
  def index
    @articles = Article.all
    render json: @articles
  end

  def show
    @article = Article.find(params[:id])
    render json: @article
  end

  def create
    @article = Article.new(article_params)

    if params[:article][:image].present?
      uploaded_file = params[:article][:image]
      cloudinary_upload = Cloudinary::Uploader.upload(uploaded_file.tempfile)
      @article.image = cloudinary_upload['secure_url']
    end

    if @article.save
      render json: @article, status: :created
    else
      render json: { errors: @article.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      render json: @article
    else
      render json: { errors: @article.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])

    if @article.destroy
      render json: { message: 'Article deleted successfully' }, status: :no_content
    else
      render json: { errors: 'Unable to delete the article' }, status: :unprocessable_entity
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :Upload_Img, :status)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #before_action :authenticate_user!

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @decorated_article = ArticlesDecorator.new(@article)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if params[:article][:image].present?
      #uploaded_file = params[:article][:image]
      cloudinary_service = CloudinaryService.new
      #cloudinary_upload = Cloudinary::Uploader.upload(uploaded_file.tempfile)
      cloudinary_upload = cloudinary_service.upload_image(params[:article][:image])
      @article.image = cloudinary_upload['secure_url']
    end
    if @article.save
      redirect_to article_path(@article), notice: 'Article created successfully'

    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path, status: :see_other
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :password, :password_confirmation, :roles)
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :Upload_Img, :status)
  end
end

app/helpers/api/v1/articles_helper.rb
module Api::V1::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: article.status || 'public' %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/articles/edit.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css"/>
    <link rel="stylesheet" href="application.css">
   </head>
<body>
  <nav>
    <div class="menu">
      <div class="logo">
        <%= link_to articles_path do %>
          <span> Blogs</span> 
        <% end %>
        <p style="color:white; ">Welcome, <strong><%= RegistrationsPresenter.new(current_user).name %></strong></p>
      </div>
    </div>
  </nav>
  <div class="img"></div>
  <div class="center">
    <div class="title" style="font-size: 30px; font-family: Aries; font-weight: 700;"> Edit Article </div>
    
    <h2 style="color:white;">
      <p style="color:white;"><%= render "form", article: @article  %></p>          
    </h2>

  </div>
  
</body>
</html>

app/views/articles/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css"/>
    <link rel="stylesheet" href="application.css">
   </head>
<body>

<% if user_signed_in? %> 
<nav> 
    <div class="menu">
      <div class="logo">
        <a href="#">Blogs</a>
        <p style="color:white; ">Welcome, <strong><%= RegistrationsPresenter.new(current_user).email %></strong></p>
      </div>
      
    </div>
  </nav>
  <div class="img"></div>
  <div class="center">
    <div class="title">Articles</div>
    <p style="color:white;">Our blog has <%= Article.public_count %> articles and counting!</p>
    
    <ul>
      <% @articles.each do |article| %>
        <% unless article.archived? %>
          <li> 
            <h1 style="color:white;">
              <div class="btns">
                <button><%= link_to article.title, article%></button>
              </div>                 
            </h1>
          </li>
        <% end %>  
      <%end%>
    </ul>

      <h2 style="color:white;">
        <div class="btns">
          <% if current_user.has_role?(:admin) %>
            <button><%= link_to "New Article", new_article_path %></button>
          <% end %>
        </div>                 
        <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
      </h2>
    
    
    

  </div>
 
<% else %>
  <div class="center">
    <div class="btns">
      <%= button_to "Sign in", new_user_session_path %> 
    </div>
  </div>
<% end %>
  
  
</body>
</html>

app/views/articles/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css"/>
    <link rel="stylesheet" href="application.css">
   </head>
<body>
  <nav>
    <div class="menu">
      <div class="logo">
        <%= link_to articles_path do %>
          <span> Blogs</span>
        <% end %>
        <p style="color:white; ">Welcome, <strong><%= RegistrationsPresenter.new(current_user).name %></strong></p>
      </div>
      
    </div>
  </nav>
  <div class="img"></div>
  <div class="center">
    <div class="title" style="font-size: 30px; font-family: Aries; font-weight: 700;"> New Article </div>
    
    <h2 style="color:white;">
      <p style="color:white;"><%= render "form", article: @article  %></p>          
    </h2>

  </div>
  
</body>
</html>

app/views/articles/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css"/>
    <link rel="stylesheet" href="application.css">

    <style>
      table {
        width: 50%;
        border: 1px solid white;
        margin-left: auto;
        margin-right: auto;
      }

      td {
        padding: 4px;
      }

      tr:nth-child(even) {
        background-color: #eee;
      }
    </style>

  </head>
<body>
  <nav>
    <div class="menu">
      <div class="logo">
        <%= link_to articles_path do %>
          <span> Blogs</span>
        <% end %>
        <p style="color:white; ">Welcome, <strong><%= RegistrationsPresenter.new(current_user).name %></strong></p>
      </div>
      
    </div>
  </nav>
  <div class="img"></div>
  <div class="center">
    <div class="title"> <%= @article.title%> </div>
    <p style="color:white;"><%= @article.body%></p>
    <% if @article.image.present? %>
              <img src="<%= @article.image %>" alt="Article Image" style="width:100px;height:100px; text-align:right;">
            <% else %>
              <p>No image available</p>
            <% end %>
            
    <ul>
      <li> 
        <h2 style="color:white;">
          <div class="btns">
          <% if current_user.has_role?(:admin) %>
            <button><%= link_to "Edit", edit_article_path(@article) %></button>
            <button><%= link_to "Delete", article_path(@article), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></button>
            <% end %>
          </div>                 
        </h2>
      </li>
    </ul>
    
    

          
    <h2 style="color:white;">
      <div class="title" style="font-size: 30px; font-family: Aries; font-weight: 500;"> <strong>Comments:</strong> (Total count: <%= @decorated_article.comment_count %> )</div> 

      <table>
        <tr>
          <th>Commenter</th>
          <th>Comment</th>
          <th>Delete</th>
        </tr>
      </table>
      
      <p style="color:white;"><%= render @article.comments %></p>          
    </h2>

    <h2 style="color:white;">
      <div class="title" style="font-size: 30px; font-family: Aries; font-weight: 500;"> Add a comment: </div> 
      <p style="color:white;"><%= render 'comments/form' %></p>             
    </h2>

  </div>
  
</body>
</html>